env:
  browser: true
  es6: true
  node: true
extends: 'eslint:recommended'
parserOptions:
  sourceType: module
rules:
  indent:
    - warn
    - 2
  linebreak-style:
    - error
    - unix
  # quotes:
  #   - error
  #   - double
  semi:
    - warn
    - always
  valid-jsdoc:
    - warn
